"""configuracoes runtime

Revision ID: 15934e8d2fb6
Revises: aaef0ad8bc26
Create Date: 2026-07-08 04:42:52.872530
"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '15934e8d2fb6'
down_revision: str | None = 'aaef0ad8bc26'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chave', sa.String(length=80), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('secreto', sa.Boolean(), nullable=False),
    sa.Column('cifrado', sa.Boolean(), nullable=False),
    sa.Column('categoria', sa.String(length=40), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracoes_chave'), 'configuracoes', ['chave'], unique=True)
    # ### end Alembic commands ###
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON configuracoes TO hubcapture_app")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuracoes_chave'), table_name='configuracoes')
    op.drop_table('configuracoes')
    # ### end Alembic commands ###
