"""base_conhecimento

Revision ID: 62d3e80134f1
Revises: 15934e8d2fb6
Create Date: 2026-07-08 05:00:23.321072
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '62d3e80134f1'
down_revision: str | None = '15934e8d2fb6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('base_conhecimento',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON base_conhecimento TO hubcapture_app")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('base_conhecimento')
    # ### end Alembic commands ###
