"""obras

Revision ID: 66ddf34515bd
Revises: 94fa3ecc38e2
Create Date: 2026-07-14 02:05:34.231677
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66ddf34515bd'
down_revision: Union[str, None] = '94fa3ecc38e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('obras',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('fonte', sa.String(length=16), nullable=False),
    sa.Column('id_externo', sa.String(length=128), nullable=False),
    sa.Column('municipio_ibge', sa.String(length=7), nullable=False),
    sa.Column('municipio_nome', sa.String(length=255), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('nome', sa.Text(), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('programa', sa.String(length=255), nullable=True),
    sa.Column('eixo', sa.String(length=32), nullable=True),
    sa.Column('situacao', sa.String(length=24), nullable=True),
    sa.Column('percentual_execucao', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('valor_investimento', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('valor_repassado', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim_prevista', sa.Date(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('orgao', sa.String(length=120), nullable=True),
    sa.Column('detalhe', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('proveniencia', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hash_conteudo', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cache_atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fonte', 'id_externo', name='uq_obras_fonte_id_externo')
    )
    op.create_index(op.f('ix_obras_cache_atualizado_em'), 'obras', ['cache_atualizado_em'], unique=False)
    op.create_index(op.f('ix_obras_fonte'), 'obras', ['fonte'], unique=False)
    op.create_index(op.f('ix_obras_municipio_ibge'), 'obras', ['municipio_ibge'], unique=False)
    op.create_index(op.f('ix_obras_situacao'), 'obras', ['situacao'], unique=False)
    # ### end Alembic commands ###

    # RLS: cache global (dado público). SELECT filtra por município de interesse;
    # INSERT/UPDATE/DELETE livres para a role de app (espelha propostas/repasses/
    # conformidades).
    uid = "current_setting('app.usuario_id', true)::uuid"
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON obras TO hubcapture_app")
    op.execute("ALTER TABLE obras ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE obras FORCE ROW LEVEL SECURITY")
    op.execute(
        f"""
        CREATE POLICY p_obras_select ON obras
          FOR SELECT
          USING (municipio_ibge IN (
            SELECT ibge FROM municipios_interesse WHERE usuario_id = {uid}
          ))
        """
    )
    op.execute("CREATE POLICY p_obras_insert ON obras FOR INSERT WITH CHECK (true)")
    op.execute("CREATE POLICY p_obras_update ON obras FOR UPDATE USING (true) WITH CHECK (true)")
    op.execute("CREATE POLICY p_obras_delete ON obras FOR DELETE USING (true)")


def downgrade() -> None:
    for pol in ("select", "insert", "update", "delete"):
        op.execute(f"DROP POLICY IF EXISTS p_obras_{pol} ON obras")
    op.execute("ALTER TABLE obras DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obras_situacao'), table_name='obras')
    op.drop_index(op.f('ix_obras_municipio_ibge'), table_name='obras')
    op.drop_index(op.f('ix_obras_fonte'), table_name='obras')
    op.drop_index(op.f('ix_obras_cache_atualizado_em'), table_name='obras')
    op.drop_table('obras')
    # ### end Alembic commands ###
