"""conformidades

Revision ID: 94fa3ecc38e2
Revises: 62d3e80134f1
Create Date: 2026-07-08 11:50:55.166604
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '94fa3ecc38e2'
down_revision: str | None = '62d3e80134f1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conformidades',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('municipio_ibge', sa.String(length=7), nullable=False),
    sa.Column('municipio_nome', sa.String(length=255), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('tipo', sa.String(length=8), nullable=False),
    sa.Column('numero', sa.String(length=16), nullable=False),
    sa.Column('secao', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('validade', sa.Date(), nullable=True),
    sa.Column('orgao', sa.String(length=120), nullable=True),
    sa.Column('valor', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('detalhe', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('proveniencia', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hash_conteudo', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cache_atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('municipio_ibge', 'tipo', 'numero', name='uq_conformidades_muni_tipo_numero')
    )
    op.create_index(op.f('ix_conformidades_cache_atualizado_em'), 'conformidades', ['cache_atualizado_em'], unique=False)
    op.create_index(op.f('ix_conformidades_municipio_ibge'), 'conformidades', ['municipio_ibge'], unique=False)
    op.create_index(op.f('ix_conformidades_tipo'), 'conformidades', ['tipo'], unique=False)
    # ### end Alembic commands ###

    # RLS: cache global (dado público). SELECT filtra por município de interesse;
    # INSERT/UPDATE/DELETE livres para a role de app (espelha propostas/repasses).
    uid = "current_setting('app.usuario_id', true)::uuid"
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON conformidades TO hubcapture_app")
    op.execute("ALTER TABLE conformidades ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE conformidades FORCE ROW LEVEL SECURITY")
    op.execute(
        f"""
        CREATE POLICY p_conformidades_select ON conformidades
          FOR SELECT
          USING (municipio_ibge IN (
            SELECT ibge FROM municipios_interesse WHERE usuario_id = {uid}
          ))
        """
    )
    op.execute("CREATE POLICY p_conformidades_insert ON conformidades FOR INSERT WITH CHECK (true)")
    op.execute("CREATE POLICY p_conformidades_update ON conformidades FOR UPDATE USING (true) WITH CHECK (true)")
    op.execute("CREATE POLICY p_conformidades_delete ON conformidades FOR DELETE USING (true)")


def downgrade() -> None:
    for pol in ("select", "insert", "update", "delete"):
        op.execute(f"DROP POLICY IF EXISTS p_conformidades_{pol} ON conformidades")
    op.execute("ALTER TABLE conformidades DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conformidades_tipo'), table_name='conformidades')
    op.drop_index(op.f('ix_conformidades_municipio_ibge'), table_name='conformidades')
    op.drop_index(op.f('ix_conformidades_cache_atualizado_em'), table_name='conformidades')
    op.drop_table('conformidades')
    # ### end Alembic commands ###
