"""initial schema

Revision ID: a7cea6e95621
Revises: 
Create Date: 2026-07-08 02:18:39.123835
"""
from collections.abc import Sequence

import fastapi_users_db_sqlalchemy
import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a7cea6e95621'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector: extensão precisa existir ANTES de qualquer coluna vector(1536).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('acao', sa.String(length=64), nullable=True),
    sa.Column('entidade', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_usuario_id'), 'audit_log', ['usuario_id'], unique=False)
    op.create_table('propostas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('fonte', sa.String(length=32), nullable=False),
    sa.Column('id_externo', sa.String(length=255), nullable=False),
    sa.Column('numero_proposta', sa.String(length=64), nullable=True),
    sa.Column('titulo', sa.Text(), nullable=True),
    sa.Column('objeto', sa.Text(), nullable=True),
    sa.Column('orgao_superior', sa.String(length=255), nullable=True),
    sa.Column('modalidade', sa.String(length=64), nullable=True),
    sa.Column('municipio_ibge', sa.String(length=7), nullable=True),
    sa.Column('municipio_nome', sa.String(length=255), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('contrapartida', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('situacao', sa.String(length=255), nullable=True),
    sa.Column('emenda', sa.String(length=64), nullable=True),
    sa.Column('prazos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pendencias', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('movimentacao', sa.Text(), nullable=True),
    sa.Column('data_atualizacao_fonte', sa.Date(), nullable=True),
    sa.Column('url_origem', sa.Text(), nullable=True),
    sa.Column('proveniencia', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resumo_ia', sa.Text(), nullable=True),
    sa.Column('hash_conteudo', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cache_atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fonte', 'id_externo', name='uq_propostas_fonte_id_externo')
    )
    op.create_index(op.f('ix_propostas_cache_atualizado_em'), 'propostas', ['cache_atualizado_em'], unique=False)
    op.create_index(op.f('ix_propostas_fonte'), 'propostas', ['fonte'], unique=False)
    op.create_index(op.f('ix_propostas_municipio_ibge'), 'propostas', ['municipio_ibge'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('fonte', sa.String(length=32), nullable=True),
    sa.Column('tipo', sa.String(length=12), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.Column('registros', sa.Integer(), nullable=True),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.CheckConstraint("tipo in ('agendado','avulso')", name='ck_sync_runs_tipo'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('senha_hash', sa.String(length=1024), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('papel', sa.String(length=20), nullable=True),
    sa.Column('plano', sa.String(length=50), nullable=True),
    sa.Column('telefone_wpp', sa.String(length=20), nullable=True),
    sa.Column('optin_wpp', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.CheckConstraint("papel in ('parlamentar','executivo','equipe')", name='ck_usuarios_papel'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('alertas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('proposta_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=32), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('lido', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposta_id'], ['propostas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_usuario_id'), 'alertas', ['usuario_id'], unique=False)
    op.create_table('favoritos',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('proposta_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposta_id'], ['propostas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'proposta_id')
    )
    op.create_table('monitoramentos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('proposta_id', sa.UUID(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('canais', postgresql.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proposta_id'], ['propostas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'proposta_id', name='uq_monitoramentos_usuario_proposta')
    )
    op.create_index(op.f('ix_monitoramentos_usuario_id'), 'monitoramentos', ['usuario_id'], unique=False)
    op.create_table('municipios_interesse',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('ibge', sa.String(length=7), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('modo', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("modo in ('monitorado','avulso')", name='ck_municipios_modo'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'ibge', name='uq_municipios_usuario_ibge')
    )
    op.create_index(op.f('ix_municipios_interesse_ibge'), 'municipios_interesse', ['ibge'], unique=False)
    op.create_index(op.f('ix_municipios_interesse_usuario_id'), 'municipios_interesse', ['usuario_id'], unique=False)
    op.create_table('pastas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cor', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pastas_usuario_id'), 'pastas', ['usuario_id'], unique=False)
    op.create_table('preferencias_usuario',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('fontes', postgresql.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('areas', postgresql.ARRAY(sa.TEXT()), nullable=True),
    sa.Column('monitorar_ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('proposta_embeddings',
    sa.Column('proposta_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.ForeignKeyConstraint(['proposta_id'], ['propostas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('proposta_id')
    )
    op.create_table('pasta_propostas',
    sa.Column('pasta_id', sa.UUID(), nullable=False),
    sa.Column('proposta_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pasta_id'], ['pastas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['proposta_id'], ['propostas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pasta_id', 'proposta_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pasta_propostas')
    op.drop_table('proposta_embeddings')
    op.drop_table('preferencias_usuario')
    op.drop_index(op.f('ix_pastas_usuario_id'), table_name='pastas')
    op.drop_table('pastas')
    op.drop_index(op.f('ix_municipios_interesse_usuario_id'), table_name='municipios_interesse')
    op.drop_index(op.f('ix_municipios_interesse_ibge'), table_name='municipios_interesse')
    op.drop_table('municipios_interesse')
    op.drop_index(op.f('ix_monitoramentos_usuario_id'), table_name='monitoramentos')
    op.drop_table('monitoramentos')
    op.drop_table('favoritos')
    op.drop_index(op.f('ix_alertas_usuario_id'), table_name='alertas')
    op.drop_table('alertas')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_propostas_municipio_ibge'), table_name='propostas')
    op.drop_index(op.f('ix_propostas_fonte'), table_name='propostas')
    op.drop_index(op.f('ix_propostas_cache_atualizado_em'), table_name='propostas')
    op.drop_table('propostas')
    op.drop_index(op.f('ix_audit_log_usuario_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
