"""planos e convites

Revision ID: aaef0ad8bc26
Revises: cc8ba56257ec
Create Date: 2026-07-08 04:23:52.335295
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aaef0ad8bc26'
down_revision: str | None = 'cc8ba56257ec'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco_mensal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('limites', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planos_slug'), 'planos', ['slug'], unique=True)
    op.create_table('convites',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=True),
    sa.Column('plano_id', sa.UUID(), nullable=True),
    sa.Column('convidado_por', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['convidado_por'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plano_id'], ['planos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convites_email'), 'convites', ['email'], unique=False)
    op.create_index(op.f('ix_convites_token'), 'convites', ['token'], unique=True)
    op.add_column('usuarios', sa.Column('plano_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_usuarios_plano_id', 'usuarios', 'planos', ['plano_id'], ['id'], ondelete='SET NULL'
    )
    # ### end Alembic commands ###

    # planos/convites são platform-level (sem RLS). A role de app precisa dos
    # privilégios de tabela (o ALTER DEFAULT PRIVILEGES do init também cobre).
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON planos TO hubcapture_app")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON convites TO hubcapture_app")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_usuarios_plano_id', 'usuarios', type_='foreignkey')
    op.drop_column('usuarios', 'plano_id')
    op.drop_index(op.f('ix_convites_token'), table_name='convites')
    op.drop_index(op.f('ix_convites_email'), table_name='convites')
    op.drop_table('convites')
    op.drop_index(op.f('ix_planos_slug'), table_name='planos')
    op.drop_table('planos')
    # ### end Alembic commands ###
