"""repasses

Revision ID: cc8ba56257ec
Revises: 0002_rls_policies
Create Date: 2026-07-08 03:29:04.668558
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'cc8ba56257ec'
down_revision: str | None = '0002_rls_policies'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repasses',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('fonte', sa.String(length=32), nullable=False),
    sa.Column('id_externo', sa.String(length=255), nullable=False),
    sa.Column('municipio_ibge', sa.String(length=7), nullable=True),
    sa.Column('municipio_nome', sa.String(length=255), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('data_repasse', sa.Date(), nullable=True),
    sa.Column('competencia', sa.String(length=32), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=255), nullable=True),
    sa.Column('orgao_superior', sa.String(length=255), nullable=True),
    sa.Column('natureza', sa.String(length=16), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('documento', sa.String(length=255), nullable=True),
    sa.Column('emenda', sa.Boolean(), nullable=False),
    sa.Column('detalhe', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('proveniencia', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hash_conteudo', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cache_atualizado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fonte', 'id_externo', name='uq_repasses_fonte_id_externo')
    )
    op.create_index(op.f('ix_repasses_cache_atualizado_em'), 'repasses', ['cache_atualizado_em'], unique=False)
    op.create_index(op.f('ix_repasses_data_repasse'), 'repasses', ['data_repasse'], unique=False)
    op.create_index(op.f('ix_repasses_fonte'), 'repasses', ['fonte'], unique=False)
    op.create_index(op.f('ix_repasses_municipio_ibge'), 'repasses', ['municipio_ibge'], unique=False)
    # ### end Alembic commands ###

    # RLS: cache global (dado público). SELECT filtra por município de interesse;
    # INSERT/UPDATE/DELETE livres para a role de app (espelha `propostas`).
    uid = "current_setting('app.usuario_id', true)::uuid"
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON repasses TO hubcapture_app")
    op.execute("ALTER TABLE repasses ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE repasses FORCE ROW LEVEL SECURITY")
    op.execute(
        f"""
        CREATE POLICY p_repasses_select ON repasses
          FOR SELECT
          USING (municipio_ibge IN (
            SELECT ibge FROM municipios_interesse WHERE usuario_id = {uid}
          ))
        """
    )
    op.execute("CREATE POLICY p_repasses_insert ON repasses FOR INSERT WITH CHECK (true)")
    op.execute("CREATE POLICY p_repasses_update ON repasses FOR UPDATE USING (true) WITH CHECK (true)")
    op.execute("CREATE POLICY p_repasses_delete ON repasses FOR DELETE USING (true)")


def downgrade() -> None:
    for pol in ("select", "insert", "update", "delete"):
        op.execute(f"DROP POLICY IF EXISTS p_repasses_{pol} ON repasses")
    op.execute("ALTER TABLE repasses DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repasses_municipio_ibge'), table_name='repasses')
    op.drop_index(op.f('ix_repasses_fonte'), table_name='repasses')
    op.drop_index(op.f('ix_repasses_data_repasse'), table_name='repasses')
    op.drop_index(op.f('ix_repasses_cache_atualizado_em'), table_name='repasses')
    op.drop_table('repasses')
    # ### end Alembic commands ###
