/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register:Register */
        post: operations["register_register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/consulta-avulsa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Consulta Avulsa Endpoint */
        post: operations["consulta_avulsa_endpoint_api_v1_consulta_avulsa_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/propostas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Propostas */
        get: operations["listar_propostas_api_v1_propostas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/propostas/{proposta_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obter Proposta */
        get: operations["obter_proposta_api_v1_propostas__proposta_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repasses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Repasses */
        get: operations["listar_repasses_api_v1_repasses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repasses/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Repasses */
        post: operations["sync_repasses_api_v1_repasses_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repasses/visao-geral": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Visao Geral */
        get: operations["visao_geral_api_v1_repasses_visao_geral_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_api_v1_auth_login_post */
        Body_login_api_v1_auth_login_post: {
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
            /** Grant Type */
            grant_type?: string | null;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Username */
            username: string;
        };
        /** ConsultaAvulsaRequest */
        ConsultaAvulsaRequest: {
            /**
             * Fonte
             * @default transferegov_ff
             */
            fonte: string;
            /**
             * Municipio Ibge
             * @description código IBGE
             */
            municipio_ibge: string;
        };
        /** ErrorModel */
        ErrorModel: {
            /** Detail */
            detail: string | {
                [key: string]: string;
            };
        };
        /**
         * FonteResumo
         * @description Card por fonte no dashboard (ícone/valor/nº de movimentações).
         */
        FonteResumo: {
            /** Fonte */
            fonte: string;
            /** Movimentacoes */
            movimentacoes: number;
            /** Total */
            total: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PropostaRead
         * @description Representação da proposta devolvida pela API.
         */
        PropostaRead: {
            /** Cache Atualizado Em */
            cache_atualizado_em?: string | null;
            /** Contrapartida */
            contrapartida?: string | null;
            /** Data Atualizacao Fonte */
            data_atualizacao_fonte?: string | null;
            /** Emenda */
            emenda?: string | null;
            /** Fonte */
            fonte: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Id Externo */
            id_externo: string;
            /** Modalidade */
            modalidade?: string | null;
            /** Movimentacao */
            movimentacao?: string | null;
            /** Municipio Ibge */
            municipio_ibge?: string | null;
            /** Municipio Nome */
            municipio_nome?: string | null;
            /** Numero Proposta */
            numero_proposta?: string | null;
            /** Objeto */
            objeto?: string | null;
            /** Orgao Superior */
            orgao_superior?: string | null;
            /** Pendencias */
            pendencias?: unknown[] | null;
            /** Prazos */
            prazos?: unknown[] | null;
            /** Proveniencia */
            proveniencia?: {
                [key: string]: unknown;
            } | null;
            /** Resumo Ia */
            resumo_ia?: string | null;
            /** Situacao */
            situacao?: string | null;
            /** Titulo */
            titulo?: string | null;
            /** Uf */
            uf?: string | null;
            /** Url Origem */
            url_origem?: string | null;
            /** Valor Total */
            valor_total?: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RepasseRead */
        RepasseRead: {
            /** Cache Atualizado Em */
            cache_atualizado_em?: string | null;
            /** Categoria */
            categoria?: string | null;
            /** Competencia */
            competencia?: string | null;
            /** Data Repasse */
            data_repasse?: string | null;
            /** Descricao */
            descricao?: string | null;
            /** Detalhe */
            detalhe?: {
                [key: string]: unknown;
            } | null;
            /** Documento */
            documento?: string | null;
            /** Emenda */
            emenda: boolean;
            /** Fonte */
            fonte: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Id Externo */
            id_externo: string;
            /** Municipio Ibge */
            municipio_ibge?: string | null;
            /** Municipio Nome */
            municipio_nome?: string | null;
            /** Natureza */
            natureza: string;
            /** Orgao Superior */
            orgao_superior?: string | null;
            /** Uf */
            uf?: string | null;
            /** Valor */
            valor?: string | null;
        };
        /**
         * RepassesPorDia
         * @description Item do feed agrupado por data, com subtotal do dia.
         */
        RepassesPorDia: {
            /**
             * Data
             * Format: date
             */
            data: string;
            /** Itens */
            itens: components["schemas"]["RepasseRead"][];
            /** Subtotal */
            subtotal: string;
        };
        /** SyncRepassesRequest */
        SyncRepassesRequest: {
            /** Fontes */
            fontes?: string[] | null;
            /** Municipio Ibge */
            municipio_ibge: string;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean | null;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean | null;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean | null;
            /** Nome */
            nome?: string | null;
            /**
             * Optin Wpp
             * @default false
             */
            optin_wpp: boolean;
            /** Papel */
            papel?: string | null;
            /** Password */
            password: string;
            /** Plano */
            plano?: string | null;
            /** Telefone Wpp */
            telefone_wpp?: string | null;
        };
        /** UserRead */
        UserRead: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Is Superuser
             * @default false
             */
            is_superuser: boolean;
            /**
             * Is Verified
             * @default false
             */
            is_verified: boolean;
            /** Nome */
            nome?: string | null;
            /**
             * Optin Wpp
             * @default false
             */
            optin_wpp: boolean;
            /** Papel */
            papel?: string | null;
            /** Plano */
            plano?: string | null;
            /** Telefone Wpp */
            telefone_wpp?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VisaoGeral
         * @description Painel consolidado: KPI + fontes + feed agrupado por data.
         */
        VisaoGeral: {
            /** Feed */
            feed: components["schemas"]["RepassesPorDia"][];
            /** Fim */
            fim?: string | null;
            /** Fontes */
            fontes: components["schemas"]["FonteResumo"][];
            /** Inicio */
            inicio?: string | null;
            /** Movimentacoes */
            movimentacoes: number;
            /** Total Pago */
            total_pago: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_api_v1_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consulta_avulsa_endpoint_api_v1_consulta_avulsa_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsultaAvulsaRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropostaRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    listar_propostas_api_v1_propostas_get: {
        parameters: {
            query?: {
                /** @description código IBGE (7 dígitos) */
                municipio?: string | null;
                fonte?: string | null;
                /** @description reservado (áreas) — futuro */
                area?: string | null;
                situacao?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropostaRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obter_proposta_api_v1_propostas__proposta_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposta_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropostaRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_repasses_api_v1_repasses_get: {
        parameters: {
            query?: {
                /** @description código IBGE (7 dígitos) */
                municipio?: string | null;
                fonte?: string | null;
                inicio?: string | null;
                fim?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepasseRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_repasses_api_v1_repasses_sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncRepassesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    visao_geral_api_v1_repasses_visao_geral_get: {
        parameters: {
            query?: {
                municipio?: string | null;
                inicio?: string | null;
                fim?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisaoGeral"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
